package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.DeletedUserEntityExample;
import com.example.demo.entity.DeletedUserEntity;

@Mapper
public interface DeletedUserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_deleted
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    long countByExample(DeletedUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_deleted
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByExample(DeletedUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_deleted
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_deleted
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insert(DeletedUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_deleted
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insertSelective(DeletedUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_deleted
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    List<DeletedUserEntity> selectByExample(DeletedUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_deleted
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExampleSelective(@Param("record") DeletedUserEntity record, @Param("example") DeletedUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_deleted
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExample(@Param("record") DeletedUserEntity record, @Param("example") DeletedUserEntityExample example);
}