package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.DeletedTalkRoomEntityExample;
import com.example.demo.entity.DeletedTalkRoomEntity;

@Mapper
public interface DeletedTalkRoomEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room_deleted
     *
     * @mbg.generated Sun May 09 21:02:38 JST 2021
     */
    long countByExample(DeletedTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room_deleted
     *
     * @mbg.generated Sun May 09 21:02:38 JST 2021
     */
    int deleteByExample(DeletedTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room_deleted
     *
     * @mbg.generated Sun May 09 21:02:38 JST 2021
     */
    int deleteByPrimaryKey(Integer talkRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room_deleted
     *
     * @mbg.generated Sun May 09 21:02:38 JST 2021
     */
    int insert(DeletedTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room_deleted
     *
     * @mbg.generated Sun May 09 21:02:38 JST 2021
     */
    int insertSelective(DeletedTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room_deleted
     *
     * @mbg.generated Sun May 09 21:02:38 JST 2021
     */
    List<DeletedTalkRoomEntity> selectByExample(DeletedTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room_deleted
     *
     * @mbg.generated Sun May 09 21:02:38 JST 2021
     */
    int updateByExampleSelective(@Param("record") DeletedTalkRoomEntity record, @Param("example") DeletedTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room_deleted
     *
     * @mbg.generated Sun May 09 21:02:38 JST 2021
     */
    int updateByExample(@Param("record") DeletedTalkRoomEntity record, @Param("example") DeletedTalkRoomEntityExample example);
}