package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.DesireUserInGroupEntityExample;
import com.example.demo.entity.DesireUserInGroupEntity;

@Mapper
public interface DesireUserInGroupEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    long countByExample(DesireUserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByExample(DesireUserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("talkRoomId") Integer talkRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insert(DesireUserInGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insertSelective(DesireUserInGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    List<DesireUserInGroupEntity> selectByExample(DesireUserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    DesireUserInGroupEntity selectByPrimaryKey(@Param("userId") Integer userId, @Param("talkRoomId") Integer talkRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExampleSelective(@Param("record") DesireUserInGroupEntity record, @Param("example") DesireUserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExample(@Param("record") DesireUserInGroupEntity record, @Param("example") DesireUserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKeySelective(DesireUserInGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_desire
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKey(DesireUserInGroupEntity record);
}