package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.DesireHaveUserEntityExample;
import com.example.demo.entity.DesireHaveUserEntity;

@Mapper
public interface DesireHaveUserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    long countByExample(DesireHaveUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByExample(DesireHaveUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("haveUserId") Integer haveUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insert(DesireHaveUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insertSelective(DesireHaveUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    List<DesireHaveUserEntity> selectByExample(DesireHaveUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    DesireHaveUserEntity selectByPrimaryKey(@Param("userId") Integer userId, @Param("haveUserId") Integer haveUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExampleSelective(@Param("record") DesireHaveUserEntity record, @Param("example") DesireHaveUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExample(@Param("record") DesireHaveUserEntity record, @Param("example") DesireHaveUserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKeySelective(DesireHaveUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_desire_list
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKey(DesireHaveUserEntity record);
}