package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.DialogueTalkRoomEntityExample;
import com.example.demo.entity.DialogueTalkRoomEntity;

@Mapper
public interface DialogueTalkRoomEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    long countByExample(DialogueTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByExample(DialogueTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByPrimaryKey(Integer talkRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insert(DialogueTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insertSelective(DialogueTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    List<DialogueTalkRoomEntity> selectByExample(DialogueTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    DialogueTalkRoomEntity selectByPrimaryKey(Integer talkRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExampleSelective(@Param("record") DialogueTalkRoomEntity record, @Param("example") DialogueTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExample(@Param("record") DialogueTalkRoomEntity record, @Param("example") DialogueTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKeySelective(DialogueTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dialogue
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKey(DialogueTalkRoomEntity record);
}