package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.GroupTalkRoomEntityExample;
import com.example.demo.entity.GroupTalkRoomEntity;

@Mapper
public interface GroupTalkRoomEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    long countByExample(GroupTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByExample(GroupTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByPrimaryKey(Integer talkRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insert(GroupTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insertSelective(GroupTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    List<GroupTalkRoomEntity> selectByExample(GroupTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    GroupTalkRoomEntity selectByPrimaryKey(Integer talkRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExampleSelective(@Param("record") GroupTalkRoomEntity record, @Param("example") GroupTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExample(@Param("record") GroupTalkRoomEntity record, @Param("example") GroupTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKeySelective(GroupTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKey(GroupTalkRoomEntity record);
    
    /**
     * 自作<br>
     * last_talk_indexカラムをインクリメントする
     * 
     * @param talkRoomId talk_room_id の値
     */
    void incrementLastTalkIndex(Integer talkRoomId);
}