package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.HaveUserEntityExample;
import com.example.demo.entity.HaveUserEntity;

@Mapper
public interface HaveUserEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	long countByExample(HaveUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int deleteByExample(HaveUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int insert(HaveUserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int insertSelective(HaveUserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	List<HaveUserEntity> selectByExample(HaveUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	HaveUserEntity selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByExampleSelective(@Param("record") HaveUserEntity record,
			@Param("example") HaveUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByExample(@Param("record") HaveUserEntity record, @Param("example") HaveUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByPrimaryKeySelective(HaveUserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table have_user_list
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByPrimaryKey(HaveUserEntity record);
}