package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.ParentTalkRoomEntityExample;
import com.example.demo.entity.ParentTalkRoomEntity;

@Mapper
public interface ParentTalkRoomEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    long countByExample(ParentTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByExample(ParentTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByPrimaryKey(Integer talkRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insert(ParentTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insertSelective(ParentTalkRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    List<ParentTalkRoomEntity> selectByExample(ParentTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExampleSelective(@Param("record") ParentTalkRoomEntity record, @Param("example") ParentTalkRoomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_room
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExample(@Param("record") ParentTalkRoomEntity record, @Param("example") ParentTalkRoomEntityExample example);
}