package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.ParentUserEntityExample;
import com.example.demo.entity.ParentUserEntity;

@Mapper
public interface ParentUserEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	long countByExample(ParentUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int deleteByExample(ParentUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int insert(ParentUserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int insertSelective(ParentUserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	List<ParentUserEntity> selectByExample(ParentUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	ParentUserEntity selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByExampleSelective(@Param("record") ParentUserEntity record,
			@Param("example") ParentUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByExample(@Param("record") ParentUserEntity record, @Param("example") ParentUserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByPrimaryKeySelective(ParentUserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByPrimaryKey(ParentUserEntity record);
}