package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.TalkEntityExample;
import com.example.demo.entity.TalkEntity;

@Mapper
public interface TalkEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	long countByExample(TalkEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int deleteByExample(TalkEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int insert(TalkEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int insertSelective(TalkEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	List<TalkEntity> selectByExample(TalkEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByExampleSelective(@Param("record") TalkEntity record, @Param("example") TalkEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	int updateByExample(@Param("record") TalkEntity record, @Param("example") TalkEntityExample example);
}