package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.dto.UserInGroupEntityExample;
import com.example.demo.entity.UserInGroupEntity;

@Mapper
public interface UserInGroupEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    long countByExample(UserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByExample(UserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int deleteByPrimaryKey(@Param("talkRoomId") Integer talkRoomId, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insert(UserInGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int insertSelective(UserInGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    List<UserInGroupEntity> selectByExample(UserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    UserInGroupEntity selectByPrimaryKey(@Param("talkRoomId") Integer talkRoomId, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExampleSelective(@Param("record") UserInGroupEntity record, @Param("example") UserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByExample(@Param("record") UserInGroupEntity record, @Param("example") UserInGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKeySelective(UserInGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_in_group
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    int updateByPrimaryKey(UserInGroupEntity record);
}