package com.example.demo.entity;

public class DeletedUserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_deleted.user_id
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_deleted.user_id
     *
     * @return the value of users_deleted.user_id
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_deleted.user_id
     *
     * @param userId the value for users_deleted.user_id
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}