package com.example.demo.entity;

import lombok.EqualsAndHashCode;

@EqualsAndHashCode
public class DialogueTalkRoomEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dialogue.talk_room_id
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	private Integer talkRoomId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dialogue.last_talk_index
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	private Integer lastTalkIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dialogue.is_enabled
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	private Boolean isEnabled;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dialogue.talk_room_id
	 * @return  the value of dialogue.talk_room_id
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public Integer getTalkRoomId() {
		return talkRoomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dialogue.talk_room_id
	 * @param talkRoomId  the value for dialogue.talk_room_id
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public void setTalkRoomId(Integer talkRoomId) {
		this.talkRoomId = talkRoomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dialogue.last_talk_index
	 * @return  the value of dialogue.last_talk_index
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public Integer getLastTalkIndex() {
		return lastTalkIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dialogue.last_talk_index
	 * @param lastTalkIndex  the value for dialogue.last_talk_index
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public void setLastTalkIndex(Integer lastTalkIndex) {
		this.lastTalkIndex = lastTalkIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dialogue.is_enabled
	 * @return  the value of dialogue.is_enabled
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public Boolean getIsEnabled() {
		return isEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dialogue.is_enabled
	 * @param isEnabled  the value for dialogue.is_enabled
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}
}