package com.example.demo.entity;

public class GroupTalkRoomEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.talk_room_id
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    private Integer talkRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_name
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.last_talk_index
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    private Integer lastTalkIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.talk_room_id
     *
     * @return the value of groups.talk_room_id
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public Integer getTalkRoomId() {
        return talkRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.talk_room_id
     *
     * @param talkRoomId the value for groups.talk_room_id
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public void setTalkRoomId(Integer talkRoomId) {
        this.talkRoomId = talkRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_name
     *
     * @return the value of groups.group_name
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_name
     *
     * @param groupName the value for groups.group_name
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.last_talk_index
     *
     * @return the value of groups.last_talk_index
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public Integer getLastTalkIndex() {
        return lastTalkIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.last_talk_index
     *
     * @param lastTalkIndex the value for groups.last_talk_index
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public void setLastTalkIndex(Integer lastTalkIndex) {
        this.lastTalkIndex = lastTalkIndex;
    }
}