package com.example.demo.entity;

public class ParentTalkRoomEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_room.talk_room_id
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    private Integer talkRoomId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_room.talk_room_id
     *
     * @return the value of talk_room.talk_room_id
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public Integer getTalkRoomId() {
        return talkRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_room.talk_room_id
     *
     * @param talkRoomId the value for talk_room.talk_room_id
     *
     * @mbg.generated Sun May 09 20:59:53 JST 2021
     */
    public void setTalkRoomId(Integer talkRoomId) {
        this.talkRoomId = talkRoomId;
    }
}