package com.example.demo.entity;

import lombok.EqualsAndHashCode;

@EqualsAndHashCode
public class ParentUserEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.user_id
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.username
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.is_enabled
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	private Integer isEnabled;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.user_id
	 * @return  the value of users.user_id
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.user_id
	 * @param userId  the value for users.user_id
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.username
	 * @return  the value of users.username
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.username
	 * @param username  the value for users.username
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
	 * @return  the value of users.password
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
	 * @param password  the value for users.password
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.is_enabled
	 * @return  the value of users.is_enabled
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public Integer getIsEnabled() {
		return isEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.is_enabled
	 * @param isEnabled  the value for users.is_enabled
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public void setIsEnabled(Integer isEnabled) {
		this.isEnabled = isEnabled;
	}
}