package com.example.demo.entity;

public class TalkEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column talk.id
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column talk.num
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column talk.useri
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	private Integer useri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column talk.message
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	private String message;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column talk.id
	 * @return  the value of talk.id
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column talk.id
	 * @param id  the value for talk.id
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column talk.num
	 * @return  the value of talk.num
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column talk.num
	 * @param num  the value for talk.num
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column talk.useri
	 * @return  the value of talk.useri
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public Integer getUseri() {
		return useri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column talk.useri
	 * @param useri  the value for talk.useri
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public void setUseri(Integer useri) {
		this.useri = useri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column talk.message
	 * @return  the value of talk.message
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column talk.message
	 * @param message  the value for talk.message
	 * @mbg.generated  Sun May 09 20:59:53 JST 2021
	 */
	public void setMessage(String message) {
		this.message = message;
	}
}