package com.example.demo.entity;

import java.util.Date;

import lombok.EqualsAndHashCode;

@EqualsAndHashCode(exclude={"timestamp"})
public class TalkEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.talk_room_id
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    private Integer talkRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.talk_index
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    private Integer talkIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.user_id
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.content
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.timestamp
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.talk_room_id
     *
     * @return the value of talk.talk_room_id
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public Integer getTalkRoomId() {
        return talkRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.talk_room_id
     *
     * @param talkRoomId the value for talk.talk_room_id
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public void setTalkRoomId(Integer talkRoomId) {
        this.talkRoomId = talkRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.talk_index
     *
     * @return the value of talk.talk_index
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public Integer getTalkIndex() {
        return talkIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.talk_index
     *
     * @param talkIndex the value for talk.talk_index
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public void setTalkIndex(Integer talkIndex) {
        this.talkIndex = talkIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.user_id
     *
     * @return the value of talk.user_id
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.user_id
     *
     * @param userId the value for talk.user_id
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.content
     *
     * @return the value of talk.content
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.content
     *
     * @param content the value for talk.content
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.timestamp
     *
     * @return the value of talk.timestamp
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.timestamp
     *
     * @param timestamp the value for talk.timestamp
     *
     * @mbg.generated Sat May 15 23:05:29 JST 2021
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}