package com.example.demo.entity;

public class UserEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_details.user_id
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_details.user_id_name
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	private String userIdName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_details.user_name
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_details.password
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_details.is_enabled
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	private Boolean isEnabled;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_details.user_id
	 * @return  the value of users_details.user_id
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_details.user_id
	 * @param userId  the value for users_details.user_id
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_details.user_id_name
	 * @return  the value of users_details.user_id_name
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public String getUserIdName() {
		return userIdName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_details.user_id_name
	 * @param userIdName  the value for users_details.user_id_name
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public void setUserIdName(String userIdName) {
		this.userIdName = userIdName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_details.user_name
	 * @return  the value of users_details.user_name
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_details.user_name
	 * @param userName  the value for users_details.user_name
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_details.password
	 * @return  the value of users_details.password
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_details.password
	 * @param password  the value for users_details.password
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_details.is_enabled
	 * @return  the value of users_details.is_enabled
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public Boolean getIsEnabled() {
		return isEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_details.is_enabled
	 * @param isEnabled  the value for users_details.is_enabled
	 * @mbg.generated  Thu May 13 13:44:19 JST 2021
	 */
	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}
}